In [1]:
#visualizing protostellar disks from 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import math
from astropy import units as u
from astropy.coordinates import SkyCoord
import astropy.coordinates as apycoords
from astroNN.gaia import gaiadr2_parallax
from mw_plot import MWPlot

import importlib
from functions import sort_functions_astrometry
importlib.reload(sort_functions_astrometry)

circumstellar_disks = pd.read_csv("data/circumstellardisks.csv")
data = pd.DataFrame(circumstellar_disks)
print(data )

C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

                     Object Category Spec_Type R_band_mag  Distance_pc  \
0    2MASSI J1628137-243139       TT       NaN       17.7       140.00
1                    49 Cet   Debris        A1        5.6        59.00
2                    61 Vir   Debris       G7V        4.2         8.50
3                    99 Her   Debris     F7+K4        4.7        15.60
4      [MR81] H alpha 17 NE       TT       M2e       16.9       150.00
5                    AA Tau       TT        M0       11.8       140.00
6                    AB Aur      HAe       A0e        7.1       144.00
7                 alpha CrB   Debris      A0 V        2.2        23.00
8                  AS 205 A       TT        K0       12.8       128.00
9                  AS 205 B       TT     K7+M0         14       128.00
10                   AS 209       TT        K5       10.4       121.00
11                   ASR 41       TT       NaN        NaN       316.00
12                   AU Mic   Debris        M1        8.9         9.94
13                 beta Leo   Debris       A3V          2        11.10
14            beta Pictoris   Debris        A5        3.9        19.30
15                 beta Tri   Debris    A5 III        2.9        38.90
16                 beta UMa   Debris       A1V        2.3        24.30
17                   BP Psc       TT       NaN       12.2       100.00
18                   BP Tau       TT        K7       11.1       140.00
19         CAHA J23056+6016     YSO?       NaN        NaN      3500.00
20                    CB 26      YSO       NaN        NaN       140.00
21                   CI Tau       TT        K7       12.3       158.00
22                   CIDA 9       TT        M4       14.5       171.00
23               CoKu Tau 1       TT        M0       16.8       140.00
24                   CQ Tau       TT        F2        8.9       100.00
25         CRBR 2422.8-3423      YSO       NaN        NaN       125.00
26                   CY Tau       TT        M1       12.5       140.00
27                   DG Tau       TT        K6       11.4       140.00
28                 DG Tau B       TT       NaN        NaN       140.00
29                   DL Tau       TT        K7       11.8       159.00
..                      ...      ...       ...        ...          ...
223                  PDS 70       TT        K5       11.3       140.00
224               PV Cephei      HAe        A5       11.1       500.00
225                 rho Vir   Debris       A0V        4.8        36.90
226                  RU Lup       TT        M0       10.2       154.00
227         RX J1615.3-3255      wTT        K5       11.2       185.00
228                  RY Tau       TT        K1       12.8       128.00
229                   SR 21       TT        G3        NaN       140.00
230                 SR 24 S       TT        K1       14.2       114.40
231                    SR 4       TT        K7       11.7       134.00
232                  Sz 114       TT        M5       14.4       162.00
233                  Sz 129       TT        K7       11.9       161.00
234                Tau Ceti   Debris      G8 V        3.5         3.60
235                  TW Hya       TT        K7       11.4        56.00
236                  TWA 25   Debris        M0       10.9        54.00
237                   TWA 7   Debris     M2 Ve         11        34.50
238                UX Tau A       TT      G5 V        NaN       140.00
239                  UY Aur       TT        K7         10       140.00
240                UZ Tau E       TT        M1       11.2       131.00
241               V1094 Sco       TT        K6       12.5       154.00
242               V4046 Sgr       TT        K5        9.6        73.00
243                V883 Ori      YSO       NaN        NaN       414.00
244                V892 Tau      HAe        B8       14.4       140.00
245                    Vega   Debris        A0        0.1         7.80
246                 WaOph 6       TT        K7         12       123.00
247                   WL 16      HAe     B8-A7        NaN       140.00
248                 WL 20 S      YSO       NaN        NaN       140.00
249                  WSB 52       TT        M0       15.8       136.00
250                  WSB 60       TT      M4.5       16.6       140.00
251                  WW Cha       TT        K5       13.3       160.00
252                zeta Lep   Debris      A0 V        3.4        21.60

     Disk Major Axis  Disk_Diameter_AU  Inclination_degrees  \
0              4.300            602.00                 86.0
1              9.800            578.00                 79.0
2             22.000            187.00                 77.0
3             15.400            240.00                 50.0
4              0.380             57.00                 20.0
5              2.300            322.00                 75.0
6             18.000           2592.00                 22.0
7              4.000             92.00                 80.0
8              0.414             53.00                 20.0
9              0.190             24.00                 66.0
10             2.300            278.00                 35.0
11            20.000           6320.00                 80.0
12            29.250            291.00                 90.0
13             7.100             79.00                 32.0
14            26.000            502.00                 90.0
15             5.600            218.00                 41.0
16             3.800             92.34                 84.0
17             1.200            120.00                 75.0
18             1.500            210.00                 30.0
19             3.000          10500.00                 10.0
20             5.500            770.00                 88.0
21             2.200            348.00                 50.0
22             0.460             79.00                 46.0
23             6.400            896.00                  NaN
24             2.900            290.00                 33.0
25             1.500            187.50                 70.0
26             3.800            532.00                 30.0
27             0.400             56.00                 31.0
28             3.930            550.00                 75.0
29             1.230            196.00                 45.0
..               ...               ...                  ...
223            2.500            350.00                 62.0
224            0.680            340.00                 62.0
225            5.000            185.00                 70.0
226            0.820            126.00                 19.0
227            1.240            230.00                 41.0
228            0.360             46.00                 65.0
229            1.400            196.00                 60.0
230            0.780             89.00                 50.0
231            0.460             62.00                 22.0
232            0.720            117.00                 21.0
233            0.940            151.00                 34.0
234           15.300             55.00                 35.0
235            8.000            448.00                  0.0
236            2.890            156.00                 75.0
237            2.030             70.00                 28.0
238            0.290             41.00                 35.0
239           30.000           4200.00                 42.0
240            1.240            162.00                 56.0
241            3.900            601.00                 53.0
242            2.500            183.00                 32.0
243            0.300            124.00                 38.0
244            0.510             71.00                 59.0
245          140.000           1092.00                  0.0
246            1.675            206.00                 47.0
247            7.000            980.00                 62.0
248            0.590             82.60                  NaN
249            0.470             64.00                 54.0
250            1.200            168.00                 42.0
251            1.320            211.20                  NaN
252            0.280              6.00                 30.0

     Resolution_elements_across  At_ref. wavelength_microns
0                          10.8                        2.10
1                          24.5                      850.00
2                           3.7                       70.00
3                           2.8                       70.00
4                           2.9                        2.20
5                          44.6                        0.60
6                         360.0                        0.57
7                           0.7                       11.20
8                          13.4                     1250.00
9                           6.1                     1250.00
10                         62.2                     1250.00
11                         97.0                        2.20
12                        585.0                        0.60
13                          1.2                      100.00
14                        520.0                        0.60
15                          1.4                       70.00
16                          0.7                      100.00
17                         40.0                        1.60
18                          1.5                     1300.39
19                         74.5                        1.60
20                         42.4                        2.20
21                         18.3                      880.00
22                          3.8                     1330.00
23                         45.7                        1.60
24                          2.5                       20.50
25                          4.3                        2.20
26                          2.5                     1300.39
27                          2.7                     2800.00
28                         28.1                        1.60
29                         10.3                     1330.00
..                          ...                         ...
223                        44.5                        2.18
224                         0.6                     1300.00
225                         1.2                       70.00
226                        32.8                     1250.00
227                         2.5                      880.00
228                         2.8                     1330.00
229                         0.6                      880.00
230                         4.3                     1330.00
231                        13.5                     1250.00
232                        15.3                     1250.00
233                        24.7                     1250.00
234                         2.6                       70.00
235                        84.6                        1.10
236                        21.0                        1.60
237                        14.8                        1.60
238                         1.0                      880.00
239                         5.2                     2720.38
240                        10.3                     1330.00
241                        19.5                     1330.00
242                        10.9                      870.00
243                        10.0                     1300.00
244                         0.6                     2700.00
245                         8.2                       70.00
246                        29.9                     1250.00
247                        43.8                        7.90
248                         0.3                     1330.00
249                        15.7                     1250.00
250                         0.5                     1330.00
251                         0.5                     3300.00
252                         0.2                       18.30

[253 rows x 10 columns]

C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\ultra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
print("Total number of protostellar disk objects: " + str(len(data)))

Total number of protostellar disk objects: 253

In [3]:
#distances to protostellar disks. Mapped to... milky way galactic?

#lets visualize the magnitude of the catalog!
#start by printing column
distance_pc = data[['Object','Distance_pc']]
print("Known Distances to protstellar disks")
distance_pc

Known Distances to protstellar disks

                     Object  Distance_pc
0    2MASSI J1628137-243139       140.00
1                    49 Cet        59.00
2                    61 Vir         8.50
3                    99 Her        15.60
4      [MR81] H alpha 17 NE       150.00
5                    AA Tau       140.00
6                    AB Aur       144.00
7                 alpha CrB        23.00
8                  AS 205 A       128.00
9                  AS 205 B       128.00
10                   AS 209       121.00
11                   ASR 41       316.00
12                   AU Mic         9.94
13                 beta Leo        11.10
14            beta Pictoris        19.30
15                 beta Tri        38.90
16                 beta UMa        24.30
17                   BP Psc       100.00
18                   BP Tau       140.00
19         CAHA J23056+6016      3500.00
20                    CB 26       140.00
21                   CI Tau       158.00
22                   CIDA 9       171.00
23               CoKu Tau 1       140.00
24                   CQ Tau       100.00
25         CRBR 2422.8-3423       125.00
26                   CY Tau       140.00
27                   DG Tau       140.00
28                 DG Tau B       140.00
29                   DL Tau       159.00
..                      ...          ...
223                  PDS 70       140.00
224               PV Cephei       500.00
225                 rho Vir        36.90
226                  RU Lup       154.00
227         RX J1615.3-3255       185.00
228                  RY Tau       128.00
229                   SR 21       140.00
230                 SR 24 S       114.40
231                    SR 4       134.00
232                  Sz 114       162.00
233                  Sz 129       161.00
234                Tau Ceti         3.60
235                  TW Hya        56.00
236                  TWA 25        54.00
237                   TWA 7        34.50
238                UX Tau A       140.00
239                  UY Aur       140.00
240                UZ Tau E       131.00
241               V1094 Sco       154.00
242               V4046 Sgr        73.00
243                V883 Ori       414.00
244                V892 Tau       140.00
245                    Vega         7.80
246                 WaOph 6       123.00
247                   WL 16       140.00
248                 WL 20 S       140.00
249                  WSB 52       136.00
250                  WSB 60       140.00
251                  WW Cha       160.00
252                zeta Lep        21.60

[253 rows x 2 columns]

In [4]:
astrometry = sort_functions_astrometry.astrometry_table(data)
#print(str(missing_dist) + " Data are missing for astrometry")
astrometry

KeyError: 'RA_J2000'

In [ ]:
sorted_objects = astrometry.sort_values(by ='Distance_pc' )
sorted_objects

In [ ]:
#load sky coordinates
c, l_rad , b_rad = sort_functions_astrometry.plot_astrometry(astrometry)
c

In [ ]:
#can we visualize this somehow? #can we gaussian fit to it somehow?

fig = plt.figure(figsize=(8,5))

ax = fig.add_subplot(1,1,1, aspect='equal')
plt.grid()
ax.scatter(c.l, c.b, s=1, color='blue', alpha=0.5)
fig.suptitle('Population of protostellar disks as a function of galactic coordinates', fontsize=14)
plt.axhline(y=0, alpha= 0.4, color='r')
plt.axvline(x=125, alpha=0.1, color='r')
plt.axvline(x=302, alpha=0.1, color='r')
plt.axvline(x=110, alpha=0.1, color='r')
ax.set_xlim(360., 0.)
ax.set_ylim(-90., 90.)
ax.set_xlabel("Galactic Longitude")
ax.set_ylabel("Galactic Latitude")

In [ ]:
fig = plt.figure(figsize=(8,5))
fig.suptitle('Projection map of the protostellar disks in Galactic coordinates', fontsize=14)
ax = fig.add_subplot(1,1,1, projection='aitoff')
ax.scatter(l_rad, b_rad, s=8, color='blue', alpha=0.5)
ax.grid()

In [ ]:
#a = [0]*len(object_magnitude)
fig = plt.figure(figsize=(20,10))
plt.scatter(astrometry['Object'], astrometry['Distance_pc'])

fig.suptitle('Plot of Protostellar disk distances', fontsize=14)

#plt.axhline(y=320, alpha= 0.4, color='r')
#plt.axhline(y=15, alpha= 0.4, color='r')

plt.xlabel('Object', fontsize=14)
plt.ylabel('Distance in Parsec', fontsize=14)

plt.yticks(np.arange(0, 3500, step=500))
plt.xticks(rotation=45, fontsize=4)

plt.grid(alpha = 0.15)
plt.show()

In [ ]:
#a = [0]*len(object_magnitude)
fig = plt.figure(figsize=(20,10))
plt.scatter(sorted_objects['Object'], sorted_objects['Distance_pc']   )

fig.suptitle('Plot of Protostellar sorted disk distances', fontsize=14)

plt.axvline(x=80, alpha= 0.4, color='r')
plt.axvline(x=204, alpha= 0.4, color='r')
plt.axvline(x=245, alpha= 0.4, color='r')
plt.axvline(x=253, alpha= 0.4, color='r')

plt.xlabel('Object', fontsize=14)
plt.ylabel('Distance in Parsec', fontsize=14)

plt.yticks(np.arange(0, 3500, step=500))
plt.xticks(rotation=45, fontsize=4)

plt.grid(alpha = 0.15)
plt.show()

#hard coded distance errors 
#0.02,   0.04,     0.5, to 1
#0 80, 81 204, 205 245,

In [ ]:
print("From the data we can say that most protostellar disks we have discovered are within 300 parsecs from Earth")
print("Orion Star Forming Region is well represented")

In [ ]:
#a = [0]*len(object_magnitude)
fig = plt.figure(figsize=(20,10))
plt.scatter(astrometry['Object'], np.log10(astrometry['Distance_pc']) )

fig.suptitle('Plot of Distances to protostellar disks', fontsize=14)

plt.xlabel('Object', fontsize=14)
plt.ylabel('Distance (log10 (Parsec))', fontsize=14)

#plt.yticks(np.arange(0, 3500, step=500))
plt.xticks(rotation=45, fontsize=4)

plt.grid(alpha = 0.15)
plt.show()

In [ ]:
plot_instance = MWPlot(mode='face-on', 
                       center=(0, 0)*u.kpc,
                       radius=6.5* u.kpc, #2.5 looks nice
                       unit=u.kpc, 
                       coord='galactic',
                       annotation=True,
                       rot180=False, 
                       grayscale=True)

# Here are some setting you can set after setting up a MWPlot instance
plot_instance.title = 'Scattering of Protostellar Disk Objects Across the Galaxy'  # plot title, or it can be None to show no title
plot_instance.fontsize = 35  # fontsize for matplotlib plotting
plot_instance.figsize = (20, 20)  # figsize for matplotlib plotting
plot_instance.dpi = 100  # dpi for matplotlib plotting
plot_instance.alpha = 0.1  # dpi for matplotlib plottin
plot_instance.cmap = 'plasma'  # matplotlib cmap: https://matplotlib.org/examples/color/colormaps_reference.html
plot_instance.clim = (0, 0.04) # colorbar range
plot_instance.imalpha = 0.90  # alpha value for the milkyway image
plot_instance.s = 125  # make the scatter points bigger
plot_instance.tight_layout = True # whether plt.tight_layout() will be run

ra = np.array(sorted_objects['RA_J2000_Deci']) #ra[0]   #np.array(astrometry['RA_J2000_Deci'])
dec = np.array(sorted_objects['DEC_J2000_Deci'])# dec[0] #np.array(astrometry['DEC_J2000_Deci'])
ra = ra * u.deg
dec = dec * u.deg

distance = (np.array(astrometry['Distance_pc'])/1000)*u.kpc

ra2, dec2, parallax, parallax_error = gaiadr2_parallax(cuts=True, keepdims=False)

parallax = parallax[0:len(ra)] 
parallax_error = parallax_error[0:len(ra)]#constrain!

distance_err = (parallax_error / parallax)/1000
c = apycoords.SkyCoord(ra=ra, dec=dec, distance=distance, frame='icrs')
distance_err = np.sort(distance_err)

# use mw_scatter instead of scatter because we want a colorbar
# need to flip the sign of x because astropy is left-handed but mw_plot is right-handed
plot_instance.mw_scatter(-c.galactic.cartesian.x, 
                         c.galactic.cartesian.y,
                         [distance_err*100 , 'Distance error assumed to be very small. Additional stellar parallax data needed.'])

plot_instance.show()